import {
  badRequest,
  currentUserId,
  isFounderUserID,
  json,
  notFound,
  optionsResponse,
  serverError,
  setLogAccountScope,
  setLogAuthUser,
  serviceClient,
  unauthorized,
  withRequestLogging,
} from "../_shared/http.ts";
import { canActAsAccount } from "../_shared/account_scope.ts";
import { compactPostForPublicList, fetchUsersByIds, mapPost } from "../_shared/mappers.ts";
import { fanoutPostToFollowerTimelines } from "../_shared/user_feed.ts";
import { sendPushToUser, usernameForUserID } from "../_shared/push.ts";
import { CopyObjectCommand, DeleteObjectsCommand, PutObjectCommand, S3Client } from "npm:@aws-sdk/client-s3@3.726.1";

const BLOCKED_AI_TEXT_TOKENS = [
  "generated by ai",
  "ai-generated",
  "ai generated",
  "made with ai",
  "made with chatgpt",
  "made with midjourney",
  "generated with midjourney",
  "generated with stable diffusion",
  "made with dall-e",
  "generated with dall-e",
  "generated with dalle",
  "created with runway",
];

const BLOCKED_NUDITY_TEXT_TOKENS = [
  "nude",
  "nudes",
  "nudity",
  "nsfw",
  "explicit",
  "porn",
  "onlyfans",
];
const GOLD_SUBSCRIPTION_IDS = new Set(["02", "scrolls.gold.monthly"]);
const ACTIVE_SUBSCRIPTION_IDS = new Set(["01", "02", "scrolls.gold.monthly"]);
const FREE_MUSIC_UPLOAD_TRACK_LIMIT = 5;
const MUSIC_UPLOAD_LIMIT_MESSAGE = `Free accounts can upload up to ${FREE_MUSIC_UPLOAD_TRACK_LIMIT} songs total. Subscribe for unlimited music uploads.`;

const REPORT_RATE_LIMIT_WINDOW_HOURS = 24;
const REPORT_RATE_LIMIT_MAX = 25;
const REPORT_TRUST_WINDOW_DAYS = 30;
const REPORT_TRUST_MIN_REVIEWED = 12;
const REPORT_TRUST_MAX_DISMISS_RATIO = 0.70;
const POST_TOMBSTONE_LOOKBACK_DAYS = 45;
const POST_TOMBSTONE_LIMIT = 200;
const POST_LIST_COLUMNS = "id, author_id, type, caption, website_url, location_city, text_body, asset_ref, asset_provider, asset_bucket, asset_object_key, cover_image_ref, cover_provider, cover_bucket, cover_object_key, aspect_ratio, created_at";
const R2_BUCKET = normalizeNullableText(Deno.env.get("CLOUDFLARE_R2_BUCKET"));
const R2_CDN_BASE_URL = normalizeBaseURL(Deno.env.get("CLOUDFLARE_R2_CDN_BASE_URL"));
const R2_ACCOUNT_ID = normalizeNullableText(Deno.env.get("CLOUDFLARE_R2_ACCOUNT_ID"));
const R2_ACCESS_KEY_ID = normalizeNullableText(Deno.env.get("CLOUDFLARE_R2_ACCESS_KEY_ID"));
const R2_SECRET_ACCESS_KEY = normalizeNullableText(Deno.env.get("CLOUDFLARE_R2_SECRET_ACCESS_KEY"));

Deno.serve((req) => withRequestLogging(req, async (log) => {
  if (req.method === "OPTIONS") return optionsResponse();
  try {
    const url = new URL(req.url);
    const parts = url.pathname.split("/").filter(Boolean);
    const last = parts[parts.length - 1] ?? "";

    const authed = await currentUserId(req);
    setLogAuthUser(log, authed);

    if (req.method === "GET" && last === "by-id") {
      return await postByID(url);
    }
    if (req.method === "GET" && last === "by-author") {
      setLogAccountScope(log, authed ?? "public-posts-by-author");
      return await postsByAuthor(url, authed);
    }
    if (req.method === "GET" && last === "rescrolls-by-author") {
      setLogAccountScope(log, authed ?? "public-rescrolls-by-author");
      return await rescrollsByAuthor(url);
    }

    if (!authed) return unauthorized();
    setLogAccountScope(log, authed);

    if (req.method === "POST" && last === "posts") return await createPost(req, authed);
    if (req.method === "POST" && last === "media") return await uploadMedia(req, authed);
    if (req.method === "POST" && last === "report") return await reportPost(req, authed);
    if (req.method === "DELETE" && last === "delete") return await deletePost(req, authed);
    if (req.method === "GET" && last === "reports") return await listPostReports(req, authed);
    if (req.method === "PATCH" && last === "review") {
      const reportID = parts[parts.length - 2] ?? "";
      return await reviewPostReport(req, authed, reportID);
    }
    if (req.method === "GET" && last === "comments") {
      const postID = parts[parts.length - 2] ?? "";
      return await commentsForPost(postID);
    }
    if (req.method === "PATCH" && last === "media") return await updateMedia(req, authed);
    if (req.method === "PATCH" && last === "cover-image") return await updateCoverImage(req, authed);
    if (req.method === "PATCH" && last === "caption") return await updateCaption(req, authed);
    return notFound();
  } catch (error) {
    return serverError(error);
  }
}));

async function createPost(req: Request, authed: string) {
  const payload = await req.json();
  const postID = String(payload.id ?? "").trim();
  const requestedAuthorID = String(payload.authorID ?? "");
  const authorID = await resolveAuthorIDForWrite(authed, requestedAuthorID);
  if (!postID) return badRequest("Post ID required.");
  if (!authorID) return unauthorized();

  const caption = String(payload.caption ?? "");
  const textBody = String(payload.textBody ?? "");
  if (containsBlockedAIText(caption) || containsBlockedAIText(textBody)) {
    return badRequest("AI-generated content is not allowed.");
  }
  if (containsBlockedNudityText(caption) || containsBlockedNudityText(textBody)) {
    return badRequest("Explicit nudity content is not allowed.");
  }

  const assetWrite = await resolveMediaWriteFromPayload(payload, {
    kind: "asset",
    authed,
    authorID,
    postID,
    requireReference: false,
    allowStreamProvider: true,
  });
  if ("error" in assetWrite) return assetWrite.error;

  const coverWrite = await resolveMediaWriteFromPayload(payload, {
    kind: "cover",
    authed,
    authorID,
    postID,
    requireReference: false,
    allowStreamProvider: false,
  });
  if ("error" in coverWrite) return coverWrite.error;

if (isPodcastCaption(payload.caption) && looksLikeVideoObjectKey(assetWrite.value.objectKey)) {
  return badRequest("Podcasts are audio-only on Scrolls.");
}

const admin = serviceClient();
if (isMusicCaption(payload.caption)) {
  if (!looksLikeMusicAudioObjectKey(assetWrite.value.objectKey)) {
    return badRequest("Music uploads must be AAC, M4A, or Apollo-bounced WAV audio.");
  }
  const allowanceError = await validateMusicUploadAllowance(admin, authorID, payload.caption);
  if (allowanceError) return allowanceError;
}

  const existing = await admin.from("posts")
    .select("id, author_id, caption, created_at")
    .eq("id", postID)
    .maybeSingle();
  if (existing.error) return badRequest(existing.error.message);
  if (existing.data) {
    if (String(existing.data.author_id ?? "") !== authorID) {
      return badRequest("Post ID conflict.");
    }
    const existingCreatedAt = normalizeCreatedAt(existing.data.created_at);
    // Fanout is best-effort: post is already created, so never fail the
    // response over a feed-distribution error.
    try {
      await fanoutPostToFollowerTimelines(admin, authorID, postID, existingCreatedAt);
    } catch (fanoutError) {
      console.error(JSON.stringify({ event: "post_fanout_error_idempotent", post_id: postID, error: String(fanoutError) }));
    }
    return json({ ok: true, idempotent: true, id: postID });
  }

  const createdAt = normalizeCreatedAt(payload.createdAt);
  const subscriptionUnlockedAt = await subscriptionUnlockedTimestampForAuthor(admin, authorID, payload.caption);
  const write = await admin.from("posts").insert({
    id: postID,
    author_id: authorID,
    type: String(payload.type),
    caption: payload.caption ?? null,
    website_url: payload.websiteURL ?? null,
    location_city: payload.locationCity ?? null,
    text_body: payload.textBody ?? null,
    asset_ref: null,
    asset_provider: assetWrite.value.provider,
    asset_bucket: assetWrite.value.bucket,
    asset_object_key: assetWrite.value.objectKey,
    cover_image_ref: null,
    cover_provider: coverWrite.value.provider,
    cover_bucket: coverWrite.value.bucket,
    cover_object_key: coverWrite.value.objectKey,
    aspect_ratio: payload.aspectRatio ?? null,
    created_at: createdAt,
    updated_at: new Date().toISOString(),
    subscription_unlocked_at: subscriptionUnlockedAt,
  });
  if (write.error) return badRequest(write.error.message);
  // Fanout is best-effort: post is already persisted, so never surface a
  // feed-distribution error to the user.
  try {
    await fanoutPostToFollowerTimelines(admin, authorID, postID, createdAt);
  } catch (fanoutError) {
    console.error(JSON.stringify({ event: "post_fanout_error", post_id: postID, error: String(fanoutError) }));
  }
  // Collaborator notifications are best-effort as well: any DB or APNs
  // failure shouldn't fail the post creation, since the row is durable.
  try {
    await notifyCollaborators(admin, postID, authorID, payload.caption);
  } catch (collabError) {
    console.error(JSON.stringify({ event: "collaborator_notification_error", post_id: postID, error: String(collabError) }));
  }
  return json({ ok: true, id: postID });
}
function normalizeCreatedAt(value: unknown): string {
  if (typeof value === "string" && value.trim()) {
    const parsed = new Date(value);
    if (!Number.isNaN(parsed.getTime())) return parsed.toISOString();
  }
  if (typeof value === "number" && Number.isFinite(value)) {
    let seconds = value;
    if (Math.abs(seconds) > 1_000_000_000_000) {
      // Defensive support for millisecond epochs.
      seconds = seconds / 1000;
    }
    if (seconds > 0 && seconds < 1_200_000_000) {
      // Swift JSONEncoder default date strategy sends seconds since Apple's reference date (2001-01-01).
      const appleReferenceEpochSeconds = Date.UTC(2001, 0, 1) / 1000;
      return new Date((seconds + appleReferenceEpochSeconds) * 1000).toISOString();
    }
    return new Date(seconds * 1000).toISOString();
  }
  return new Date().toISOString();
}

async function uploadMedia(req: Request, authed: string) {
  const contentTypeHeader = (req.headers.get("content-type") ?? "").toLowerCase();
  const url = new URL(req.url);
  const payload = contentTypeHeader.includes("application/json")
    ? await req.json()
    : null;

  const requestedAuthorID = String(
    payload?.authorID ??
      url.searchParams.get("authorID") ??
      req.headers.get("x-scrolls-author-id") ??
      "",
  ).trim();
  const authorID = await resolveAuthorIDForWrite(authed, requestedAuthorID);
  if (!authorID) return unauthorized();

  const postID = String(
    payload?.postID ??
      url.searchParams.get("postID") ??
      req.headers.get("x-scrolls-post-id") ??
      "",
  ).trim();
  if (!postID) return badRequest("postID is required.");

  const kind = String(
    payload?.type ??
      url.searchParams.get("type") ??
      req.headers.get("x-scrolls-media-type") ??
      "",
  ).toLowerCase();
  if (kind !== "photo" && kind !== "video") {
    return badRequest("Unsupported media type.");
  }

  const fileName = String(
    payload?.fileName ??
      url.searchParams.get("fileName") ??
      req.headers.get("x-scrolls-file-name") ??
      "",
  ).trim();
  if (!fileName) return badRequest("fileName is required.");

  let binary: Uint8Array;
  if (payload) {
    const dataBase64 = String(payload.dataBase64 ?? "");
    if (!dataBase64) return badRequest("dataBase64 is required.");
    try {
      binary = Uint8Array.from(atob(dataBase64), (char) => char.charCodeAt(0));
    } catch {
      return badRequest("Invalid base64 payload.");
    }
  } else {
    try {
      binary = new Uint8Array(await req.arrayBuffer());
    } catch {
      return badRequest("Could not read media payload.");
    }
  }

  if (binary.byteLength === 0) return badRequest("Uploaded media is empty.");

  const admin = serviceClient();
  const userRow = await admin.from("users").select("is_founder").eq("id", authorID).maybeSingle();
  if (userRow.error) return badRequest(userRow.error.message);
  const isFounder = Boolean(userRow.data?.is_founder ?? false);

  if (!isFounder && binary.byteLength > 50 * 1024 * 1024) {
    return badRequest("Uploaded media is too large.");
  }

  const extension = fileName.includes(".") ? fileName.split(".").pop()!.toLowerCase() : "";
  const contentType =
    kind === "photo"
      ? (extension === "png" ? "image/png" : "image/jpeg")
      : (extension === "mov" ? "video/quicktime" : "video/mp4");

  const storagePath = `${authorID}/${postID}/${kind}-${Date.now()}.${extension || (kind === "photo" ? "jpg" : "mp4")}`;
  const bucket = isFounder ? "founder-post-media" : "post-media";
  const upload = await admin.storage
    .from(bucket)
    .upload(storagePath, binary, {
      upsert: true,
      contentType,
      cacheControl: "31536000",
    });
  if (upload.error) return badRequest(upload.error.message);

  const publicURL = admin.storage.from(bucket).getPublicUrl(storagePath).data.publicUrl;
  if (!publicURL) return badRequest("Failed to build media URL.");
  return json({ assetRef: publicURL });
}

function containsBlockedAIText(value: string): boolean {
  const normalized = value.toLowerCase();
  return BLOCKED_AI_TEXT_TOKENS.some((token) => normalized.includes(token));
}

async function resolveAuthorIDForWrite(authedRaw: string, requestedRaw: string): Promise<string | null> {
  const authed = String(authedRaw ?? "").trim().toLowerCase();
  const requested = String(requestedRaw ?? "").trim().toLowerCase();
  if (!authed) return null;
  if (requested && await canActAsAccount(authed, requested)) {
    return requested;
  }
  // Fallback to authenticated account to avoid stale client account-ID windows causing
  // hard publish failures; this preserves security by never allowing cross-account spoofing.
  return authed;
}

function containsBlockedNudityText(value: string): boolean {
  const normalized = value.toLowerCase();
  return BLOCKED_NUDITY_TEXT_TOKENS.some((token) => normalized.includes(token));
}

function isPodcastCaption(rawCaption: unknown): boolean {
  const caption = String(rawCaption ?? "").trim().toUpperCase();
  return caption.startsWith("[PODCAST]");
}

function isMusicCaption(rawCaption: unknown): boolean {
  const caption = String(rawCaption ?? "").trim().toUpperCase();
  return caption.startsWith("[MUSIC]");
}

/// Marker line prefixes that carry structured metadata, not
/// user-visible text.  Excluded from the visible-caption length check
/// so a music post with linked videos, lyrics, liner notes, release
/// date, etc. doesn't blow past the 220-char limit on a long marker
/// payload that the user never sees.  Plain photo/video/text posts
/// can also embed the carousel + collaborator markers, so those are
/// stripped from any caption shape.
const STRUCTURED_CAPTION_MARKER_PREFIXES = [
  "[AUDIO_LOOP_VIDEO]",
  "[MUSIC_LOOP_VIDEO]",
  "[MUSIC_RELEASE_TYPE]",
  "[MUSIC_TRACKS_BASE64]",
  "[MUSIC_RELEASE_DATE]",
  "[MUSIC_RECORD_LABEL]",
  "[MUSIC_LINER_NOTES_BASE64]",
  "[MUSIC_VIDEO_LINKS_BASE64]",
  "[PHOTO_CAROUSEL_BASE64]",
  "[SCROLL_COLLABORATORS_BASE64]",
];

function stripStructuredMarkerLines(body: string): string {
  return body
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => {
      if (line.length === 0) return false;
      const upper = line.toUpperCase();
      for (const prefix of STRUCTURED_CAPTION_MARKER_PREFIXES) {
        if (upper.startsWith(prefix)) return false;
      }
      return true;
    })
    .join("\n")
    .trim();
}

function visibleCaptionForValidation(rawCaption: string): string {
  const trimmed = rawCaption.trim();
  if (!trimmed) return "";

  const extractStructuredAudioDisplayCaption = (prefix: string): string => {
    const remainder = trimmed.slice(prefix.length).trim();
    if (!remainder) return "";
    return stripStructuredMarkerLines(remainder);
  };

  const upper = trimmed.toUpperCase();
  if (upper.startsWith("[PODCAST]")) {
    return extractStructuredAudioDisplayCaption("[PODCAST]");
  }
  if (upper.startsWith("[MUSIC]")) {
    return extractStructuredAudioDisplayCaption("[MUSIC]");
  }
  if (upper.startsWith("[ARTICLE]")) {
    return trimmed.slice("[ARTICLE]".length).trim();
  }
  // Plain captions (photo / video / text posts) can also carry the
  // carousel and collaborator markers — strip those too before the
  // length count so adding 1-4 collaborators or a 4-photo carousel
  // doesn't trip the 220-char limit.
  return stripStructuredMarkerLines(trimmed);
}

/// Pull the list of collaborator UUIDs the iOS client packed into the
/// caption under the `[SCROLL_COLLABORATORS_BASE64]` marker.  Mirrors
/// `FeedPost.scrollCollaboratorIDs` in ScrollsModels.swift.  Returns an
/// empty array on any decoding failure so callers can treat the absence
/// of a marker and a malformed marker the same way.
function collaboratorIDsFromCaption(rawCaption: unknown): string[] {
  const trimmed = String(rawCaption ?? "").trim();
  if (!trimmed) return [];
  const marker = "[SCROLL_COLLABORATORS_BASE64]";
  for (const rawLine of trimmed.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line) continue;
    if (!line.toUpperCase().startsWith(marker)) continue;
    const suffix = line.slice(marker.length).trim();
    if (!suffix) return [];
    try {
      const decoded = atob(suffix);
      const parsed = JSON.parse(decoded);
      if (!Array.isArray(parsed)) return [];
      const ids: string[] = [];
      for (const entry of parsed) {
        const id = String(entry ?? "").trim().toLowerCase();
        // Light UUID shape check — backend RLS / FK constraints will
        // reject anything that isn't a real user_id anyway, but skipping
        // obvious junk here saves a round-trip.
        if (/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(id)) {
          ids.push(id);
        }
      }
      return ids;
    } catch {
      return [];
    }
  }
  return [];
}

/// Insert one notification row per tagged collaborator (excluding the
/// post author themselves) and fire an APNs push for each.  Best-effort:
/// any DB / push failures are logged but never surfaced to the caller,
/// since the post is already persisted at this point.
async function notifyCollaborators(
  admin: ReturnType<typeof serviceClient>,
  postID: string,
  authorID: string,
  caption: unknown,
): Promise<void> {
  const ids = collaboratorIDsFromCaption(caption);
  if (ids.length === 0) return;
  const authorIDNormalized = String(authorID ?? "").trim().toLowerCase();
  // Dedupe + drop the author so we never notify someone for tagging
  // themselves (the iOS picker already filters this, but defense in
  // depth keeps a malformed payload from spamming the author).
  const recipients = Array.from(new Set(ids)).filter((id) => id && id !== authorIDNormalized);
  if (recipients.length === 0) return;

  // Only notify users that actually exist — a stale UUID from a deleted
  // account shouldn't create an orphan notification row.
  const lookup = await admin.from("users").select("id").in("id", recipients);
  if (lookup.error) {
    console.error(JSON.stringify({
      event:   "collaborator_lookup_error",
      post_id: postID,
      error:   lookup.error.message,
    }));
    return;
  }
  const validRecipients = (lookup.data ?? [])
    .map((row) => String((row as { id?: unknown }).id ?? "").trim().toLowerCase())
    .filter(Boolean);
  if (validRecipients.length === 0) return;

  const actorUsername = await usernameForUserID(admin, authorIDNormalized);
  const nowISO = new Date().toISOString();
  const rows = validRecipients.map((recipient) => ({
    user_id:    recipient,
    type:       "collaborated",
    actor_id:   authorIDNormalized,
    object_id:  postID,
    title:      actorUsername ? `Tagged by @${actorUsername}` : "You were tagged",
    message:    actorUsername
      ? `@${actorUsername} tagged you as a collaborator on their scroll.`
      : "You were tagged as a collaborator on a scroll.",
    is_read:    false,
    created_at: nowISO,
  }));

  const insert = await admin.from("notifications").insert(rows);
  if (insert.error) {
    console.error(JSON.stringify({
      event:   "collaborator_notification_insert_error",
      post_id: postID,
      error:   insert.error.message,
    }));
    // Still try the push fanout — even without an in-app row, the user
    // should learn they were tagged.
  }

  const pushBody = actorUsername
    ? `@${actorUsername} tagged you as a collaborator on their scroll.`
    : "You were tagged as a collaborator on a scroll.";
  await Promise.allSettled(
    validRecipients.map((recipient) =>
      sendPushToUser(admin, recipient, {
        title:    "Tagged on a scroll",
        body:     pushBody,
        threadId: `scroll-${postID}`,
        custom:   { scroll_url: `scrolls://scroll/${postID}` },
      })
    ),
  );
}

function looksLikeMusicAudioObjectKey(objectKey: unknown): boolean {
  const raw = String(objectKey ?? "").trim().toLowerCase().split("?")[0];
  if (!raw) return false;
  return raw.endsWith(".aac") || raw.endsWith(".m4a") || raw.endsWith(".wav");
}

function looksLikeVideoObjectKey(objectKey: unknown): boolean {
  const raw = String(objectKey ?? "").trim().toLowerCase().split("?")[0];
  if (!raw) return false;
  return raw.endsWith(".mp4") || raw.endsWith(".mov") || raw.endsWith(".m4v") || raw.endsWith(".webm");
}


async function userHasFounderAccess(admin: ReturnType<typeof serviceClient>, userIDRaw: string): Promise<boolean> {
  const userID = String(userIDRaw ?? "").trim().toLowerCase();
  if (!userID) return false;
  if (isFounderUserID(userID)) return true;
  const row = await admin.from("users").select("is_founder").eq("id", userID).maybeSingle();
  if (row.error) return false;
  return Boolean(row.data?.is_founder ?? false);
}

function isGoldSubscriptionPlan(plan: unknown): boolean {
  const normalized = String(plan ?? "").trim().toLowerCase();
  return GOLD_SUBSCRIPTION_IDS.has(normalized) || normalized.startsWith("scrolls.gold");
}

function isAnyActiveSubscriptionPlan(plan: unknown): boolean {
  const normalized = String(plan ?? "").trim().toLowerCase();
  return ACTIVE_SUBSCRIPTION_IDS.has(normalized)
    || normalized.startsWith("scrolls.gold")
    || normalized.startsWith("scrolls.blue")
    || normalized.startsWith("scrolls.verified")
    || normalized.startsWith("verification");
}

function hasActiveSubscriptionExpiry(expiresRaw: unknown): boolean {
  if (!expiresRaw) return true;
  const expires = new Date(String(expiresRaw));
  return Number.isFinite(expires.valueOf()) && expires > new Date();
}

async function userHasUnlimitedMusicUploads(admin: ReturnType<typeof serviceClient>, userIDRaw: string): Promise<boolean> {
  const userID = String(userIDRaw ?? "").trim().toLowerCase();
  if (!userID) return false;
  if (isFounderUserID(userID)) return true;
  const row = await admin.from("users")
    .select("is_founder, is_verified, subscription_plan, subscription_expires_at")
    .eq("id", userID)
    .maybeSingle();
  if (row.error || !row.data) return false;
  const data = row.data as Record<string, unknown>;
  if (Boolean(data.is_founder ?? false)) return true;
  if (Boolean(data.is_verified ?? false)) return true;
  return isAnyActiveSubscriptionPlan(data.subscription_plan) && hasActiveSubscriptionExpiry(data.subscription_expires_at);
}

function musicTrackCountForCaption(caption: unknown): number {
  if (!isMusicCaption(caption)) return 0;
  const tracks = parseMusicTrackMetadata(typeof caption === "string" ? caption : null);
  return Math.max(1, tracks.length);
}

async function countUploadedMusicTracksForAuthor(
  admin: ReturnType<typeof serviceClient>,
  authorIDRaw: string,
  excludingPostIDRaw: string | null = null,
): Promise<number> {
  const authorID = String(authorIDRaw ?? "").trim().toLowerCase();
  const excludingPostID = String(excludingPostIDRaw ?? "").trim().toLowerCase();
  if (!authorID) return 0;
  const pageSize = 1000;
  let from = 0;
  let total = 0;

  while (true) {
    const page = await admin.from("posts")
      .select("id, caption")
      .eq("author_id", authorID)
      .is("deleted_at", null)
      .range(from, from + pageSize - 1);
    if (page.error) throw page.error;
    const rows = page.data ?? [];
    for (const row of rows) {
      if (excludingPostID && String((row as Record<string, unknown>).id ?? "").trim().toLowerCase() === excludingPostID) {
        continue;
      }
      total += musicTrackCountForCaption((row as Record<string, unknown>).caption);
    }
    if (rows.length < pageSize) break;
    from += pageSize;
  }

  return total;
}

async function validateMusicUploadAllowance(
  admin: ReturnType<typeof serviceClient>,
  authorID: string,
  caption: unknown,
  excludingPostID: string | null = null,
): Promise<Response | null> {
  const newTrackCount = musicTrackCountForCaption(caption);
  if (newTrackCount <= 0) return null;
  if (await userHasUnlimitedMusicUploads(admin, authorID)) return null;

  const existingTrackCount = await countUploadedMusicTracksForAuthor(admin, authorID, excludingPostID);
  if (existingTrackCount + newTrackCount <= FREE_MUSIC_UPLOAD_TRACK_LIMIT) return null;

  const remaining = Math.max(0, FREE_MUSIC_UPLOAD_TRACK_LIMIT - existingTrackCount);
  const remainingNoun = remaining === 1 ? "song" : "songs";
  if (remaining > 0) {
    return unauthorized(`You have ${remaining} free music ${remainingNoun} left. Subscribe for unlimited music uploads.`);
  }
  return unauthorized(MUSIC_UPLOAD_LIMIT_MESSAGE);
}

function isSubscriptionUnlockedCaption(rawCaption: unknown): boolean {
  return isArticleCaption(rawCaption) || isMusicCaption(rawCaption) || isPodcastCaption(rawCaption);
}

function isArticleCaption(rawCaption: unknown): boolean {
  const caption = String(rawCaption ?? "").trim().toUpperCase();
  return caption.startsWith("[ARTICLE]");
}

async function subscriptionUnlockedTimestampForAuthor(
  admin: ReturnType<typeof serviceClient>,
  authorIDRaw: string,
  caption: unknown,
): Promise<string | null> {
  if (!isSubscriptionUnlockedCaption(caption)) return null;
  const authorID = String(authorIDRaw ?? "").trim().toLowerCase();
  if (!authorID || isFounderUserID(authorID)) return null;
  const row = await admin.from("users")
    .select("is_founder, subscription_plan, subscription_expires_at")
    .eq("id", authorID)
    .maybeSingle();
  if (row.error || !row.data) return null;
  const data = row.data as Record<string, unknown>;
  if (Boolean(data.is_founder ?? false)) return null;
  if (!isGoldSubscriptionPlan(data.subscription_plan) || !hasActiveSubscriptionExpiry(data.subscription_expires_at)) {
    return null;
  }
  return new Date().toISOString();
}

async function deletePost(req: Request, authed: string) {
  const payload = await req.json();
  const requestedAuthorID = String(payload.authorID ?? "").trim().toLowerCase();
  const postID = String(payload.postID ?? "");
  const admin = serviceClient();
  const founderOverride = await userHasFounderAccess(admin, authed);

  const existing = await admin.from("posts")
    .select("author_id, asset_ref, asset_provider, asset_bucket, asset_object_key, cover_image_ref, cover_provider, cover_bucket, cover_object_key, caption")
    .eq("id", postID)
    .maybeSingle();
  if (existing.error) return badRequest(existing.error.message);

  const actualAuthorID = existing.data
    ? String((existing.data as Record<string, unknown>).author_id ?? "").trim().toLowerCase()
    : requestedAuthorID;
  const canDeleteRequestedAuthor = requestedAuthorID ? await canActAsAccount(authed, requestedAuthorID) : false;
  const canDeleteActualAuthor = actualAuthorID ? await canActAsAccount(authed, actualAuthorID) : false;
  if (!founderOverride && !canDeleteRequestedAuthor && !canDeleteActualAuthor) return unauthorized();

  const writeDeletionTombstone = async () => {
    const tombstoneWrite = await admin.from("deleted_post_tombstones").upsert({
      post_id: postID,
      author_id: actualAuthorID || requestedAuthorID,
      deleted_at: new Date().toISOString(),
    }, { onConflict: "post_id" });
    if (tombstoneWrite.error) return badRequest(tombstoneWrite.error.message);
    return null;
  };

  if (!existing.data) {
    // The row may already be gone, but stale clients still need a fresh purge
    // signal. Re-upsert the tombstone and clear any dangling feed/rescroll rows
    // so "delete again" still repairs old caches across devices.
    const tombstoneError = await writeDeletionTombstone();
    if (tombstoneError) return tombstoneError;
    await admin.from("rescrolls").delete().eq("original_post_id", postID);
    await admin.from("user_feed_items").delete().eq("post_id", postID);
    return json({ ok: true });
  }

  // CRITICAL ORDERING: write the tombstone and hard-delete the row BEFORE any
  // storage purging. Music posts can carry many files (album cover + several
  // audio tracks across two buckets and two folder prefix conventions), and the
  // storage list+remove loop can be slow enough to exhaust the edge function
  // wall-clock. If we purge first and time out, the row stays visible on
  // followers' feeds and in search forever. Tombstone-first guarantees that a
  // partial run still hides the post everywhere; the storage sweep is then a
  // best-effort cleanup that can be retried safely (the row is already gone).
  const legacyRefs = collectLegacyRefs(
    existing.data.asset_ref,
    existing.data.cover_image_ref,
    ...parseMusicTrackMetadata(typeof existing.data.caption === "string" ? existing.data.caption : null)
      .map((track) => track.audioURL)
      .filter((value): value is string => typeof value === "string" && value.trim().length > 0),
  );
  const structuredRefs = [
    ...collectStructuredRefs(existing.data.asset_provider, existing.data.asset_bucket, existing.data.asset_object_key),
    ...collectStructuredRefs(existing.data.cover_provider, existing.data.cover_bucket, existing.data.cover_object_key),
  ];

  // 1. Tombstone first — instantly hides the post from search and feeds even if
  //    everything downstream times out.
  const tombstoneError = await writeDeletionTombstone();
  if (tombstoneError) return tombstoneError;

  // 2. Hard-delete the posts row. Cascade FKs handle post_likes, comments,
  //    rescrolls, post_reports, ad_review_queue, and user_feed_items
  //    automatically, but we still explicitly clear rescrolls/user_feed_items
  //    below as a belt-and-suspenders measure against any rows whose cascade
  //    triggers are disabled in this environment.
  const deleted = await admin.from("posts")
    .delete()
    .eq("id", postID);
  if (deleted.error) return badRequest(deleted.error.message);

  const rescrollDelete = await admin.from("rescrolls")
    .delete()
    .eq("original_post_id", postID);
  if (rescrollDelete.error) {
    // The row is already gone and the tombstone is in place — don't bubble this
    // up as a hard failure. Log and continue so the client doesn't endlessly
    // retry a delete that has effectively succeeded.
    console.warn(JSON.stringify({
      event: "delete_post_rescroll_purge_failed",
      post_id: postID,
      message: rescrollDelete.error.message,
    }));
  }

  const feedItemDelete = await admin.from("user_feed_items")
    .delete()
    .eq("post_id", postID);
  if (feedItemDelete.error) {
    console.warn(JSON.stringify({
      event: "delete_post_feed_item_purge_failed",
      post_id: postID,
      message: feedItemDelete.error.message,
    }));
  }

  // 3. Best-effort storage purge LAST. If we time out here, the post is
  //    already invisible everywhere; the iOS client's retry will hit the
  //    !existing.data branch above and re-attempt the tombstone — orphan
  //    storage objects get reclaimed by the storage-orphan-sweep cron.
  try {
    const legacyFolderPrefix = `${actualAuthorID}/${postID}`;
    const typedFolderPrefix = `posts/${actualAuthorID}/${postID}`;
    const bucketsToCheck = ["post-media", "founder-post-media"];
    for (const bucket of bucketsToCheck) {
      for (const prefix of [legacyFolderPrefix, typedFolderPrefix]) {
        const listed = await admin.storage.from(bucket).list(prefix, { limit: 200 });
        if (!listed.error && listed.data && listed.data.length > 0) {
          const paths = listed.data.map((f) => `${prefix}/${f.name}`);
          // Remove in batches of 50 to stay within API limits.
          for (let i = 0; i < paths.length; i += 50) {
            await admin.storage.from(bucket).remove(paths.slice(i, i + 50));
          }
        }
      }
    }
    await quarantineDeletedPostStorageRefs(admin, legacyRefs, structuredRefs, {
      postID,
      authorID: actualAuthorID || requestedAuthorID,
    });
  } catch (storageError) {
    console.warn(JSON.stringify({
      event: "delete_post_storage_purge_failed",
      post_id: postID,
      message: storageError instanceof Error ? storageError.message : String(storageError),
    }));
  }

  return json({ ok: true });
}

async function reportPost(req: Request, authed: string) {
  const payload = await req.json();
  const postID = String(payload.postID ?? "").trim();
  const reason = String(payload.reason ?? "").trim().toLowerCase();
  const notes = String(payload.notes ?? "").trim();
  if (!postID) return badRequest("postID is required.");
  if (![
    "drugs",
    "violence",
    "nudity_sexual_themes",
    "spam",
    "harassment_bullying",
    "hate_speech_discrimination",
    "misinformation",
    "copyright_violation",
    "impersonation",
  ].includes(reason)) {
    return badRequest("Invalid report reason.");
  }

  const admin = serviceClient();
  const blocked = await isReporterTemporarilyBlocked(admin, authed);
  if (blocked) {
    return badRequest("Reporting is temporarily limited due to high false-report activity.");
  }
  const rateLimited = await isReporterRateLimited(admin, authed);
  if (rateLimited) {
    return badRequest("You've reached the report limit. Please try again later.");
  }

  const post = await admin.from("posts").select("id, author_id, caption").eq("id", postID).is("deleted_at", null).maybeSingle();
  if (post.error) return badRequest(post.error.message);
  if (!post.data) return badRequest("Post not found.");
  if (String(post.data.author_id) === authed) return badRequest("Cannot report your own post.");

  const write = await admin.from("post_reports").upsert({
    post_id: postID,
    reporter_id: authed,
    reason,
    notes: notes || null,
    status: "pending",
    reviewed_by: null,
    reviewed_at: null,
    updated_at: new Date().toISOString(),
  }, { onConflict: "post_id,reporter_id" });
  if (write.error) return badRequest(write.error.message);

  await syncPostReportCount(admin, postID);
  return json({ ok: true });
}

async function isReporterRateLimited(admin: ReturnType<typeof serviceClient>, reporterID: string): Promise<boolean> {
  const cutoffISO = new Date(Date.now() - (REPORT_RATE_LIMIT_WINDOW_HOURS * 60 * 60 * 1000)).toISOString();
  const recent = await admin.from("post_reports")
    .select("id", { count: "exact", head: true })
    .eq("reporter_id", reporterID)
    .gte("created_at", cutoffISO);
  if (recent.error) return false;
  return Number(recent.count ?? 0) >= REPORT_RATE_LIMIT_MAX;
}

async function isReporterTemporarilyBlocked(admin: ReturnType<typeof serviceClient>, reporterID: string): Promise<boolean> {
  const cutoffISO = new Date(Date.now() - (REPORT_TRUST_WINDOW_DAYS * 24 * 60 * 60 * 1000)).toISOString();
  const reviewed = await admin.from("post_reports")
    .select("status")
    .eq("reporter_id", reporterID)
    .in("status", ["confirmed", "dismissed"])
    .gte("updated_at", cutoffISO);
  if (reviewed.error) return false;
  const rows = reviewed.data ?? [];
  if (rows.length < REPORT_TRUST_MIN_REVIEWED) return false;
  const dismissed = rows.filter((row) => String(row.status) === "dismissed").length;
  const dismissRatio = dismissed / rows.length;
  return dismissRatio >= REPORT_TRUST_MAX_DISMISS_RATIO;
}

async function listPostReports(req: Request, authed: string) {
  const admin = serviceClient();
  const actor = await admin.from("users").select("is_founder, is_admin").eq("id", authed).maybeSingle();
  if (actor.error) return badRequest(actor.error.message);
  const isAdmin = Boolean(actor.data?.is_founder ?? false) || Boolean(actor.data?.is_admin ?? false);
  if (!isAdmin) return unauthorized();

  const url = new URL(req.url);
  const status = String(url.searchParams.get("status") ?? "pending").trim().toLowerCase();
  const limit = Math.max(1, Math.min(200, Number(url.searchParams.get("limit") ?? "100")));

  let query = admin.from("post_reports")
    .select("*")
    .order("created_at", { ascending: false })
    .limit(limit);
  if (status && ["pending", "confirmed", "dismissed"].includes(status)) {
    query = query.eq("status", status);
  }
  const reports = await query;
  if (reports.error) return badRequest(reports.error.message);

  const rows = reports.data ?? [];
  const postIDs = Array.from(new Set(rows.map((row) => String(row.post_id))));
  const reporterIDs = Array.from(new Set(rows.map((row) => String(row.reporter_id))));
  const reviewerIDs = Array.from(new Set(rows.map((row) => String(row.reviewed_by ?? "")).filter(Boolean)));

  const [posts, reporters, reviewers] = await Promise.all([
    postIDs.length ? admin.from("posts").select("id, author_id, caption, text_body, created_at").in("id", postIDs) : Promise.resolve({ data: [], error: null }),
    reporterIDs.length ? fetchUsersByIds(reporterIDs) : Promise.resolve({}),
    reviewerIDs.length ? fetchUsersByIds(reviewerIDs) : Promise.resolve({}),
  ]);
  if ("error" in posts && posts.error) return badRequest(posts.error.message);

  const postMap: Record<string, Record<string, unknown>> = {};
  for (const post of (posts.data ?? [])) {
    postMap[String(post.id)] = post as Record<string, unknown>;
  }
  const authorIDs = Array.from(new Set((posts.data ?? []).map((post) => String(post.author_id))));
  const authors = authorIDs.length ? await fetchUsersByIds(authorIDs) : {};

  const payload = rows.map((row) => {
    const postRow = postMap[String(row.post_id)];
    const authorID = postRow ? String(postRow.author_id ?? "") : "";
    return {
      id: String(row.id),
      postID: String(row.post_id),
      reporterID: String(row.reporter_id),
      reporter: reporters[String(row.reporter_id)] ?? null,
      reason: String(row.reason ?? "nudity_sexual_themes"),
      notes: row.notes ? String(row.notes) : null,
      status: String(row.status ?? "pending"),
      reviewedBy: row.reviewed_by ? String(row.reviewed_by) : null,
      reviewer: row.reviewed_by ? (reviewers[String(row.reviewed_by)] ?? null) : null,
      reviewedAt: row.reviewed_at ? new Date(String(row.reviewed_at)).toISOString() : null,
      createdAt: new Date(String(row.created_at)).toISOString(),
      updatedAt: new Date(String(row.updated_at)).toISOString(),
      post: postRow ? {
        id: String(postRow.id ?? ""),
        caption: postRow.caption ? String(postRow.caption) : null,
        textBody: postRow.text_body ? String(postRow.text_body) : null,
        createdAt: postRow.created_at ? new Date(String(postRow.created_at)).toISOString() : null,
      } : null,
      postAuthor: authorID ? (authors[authorID] ?? null) : null,
    };
  });
  return json(payload);
}

async function reviewPostReport(req: Request, authed: string, reportID: string) {
  const payload = await req.json();
  const status = String(payload.status ?? "").trim().toLowerCase();
  if (!reportID) return badRequest("reportID required.");
  if (!["confirmed", "dismissed"].includes(status)) return badRequest("Invalid status.");

  const admin = serviceClient();
  const actor = await admin.from("users").select("is_founder, is_admin").eq("id", authed).maybeSingle();
  if (actor.error) return badRequest(actor.error.message);
  const isAdmin = Boolean(actor.data?.is_founder ?? false) || Boolean(actor.data?.is_admin ?? false);
  if (!isAdmin) return unauthorized();

  const existing = await admin.from("post_reports").select("id, post_id").eq("id", reportID).maybeSingle();
  if (existing.error) return badRequest(existing.error.message);
  if (!existing.data) return badRequest("Report not found.");

  const write = await admin.from("post_reports").update({
    status,
    reviewed_by: authed,
    reviewed_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }).eq("id", reportID);
  if (write.error) return badRequest(write.error.message);

  await syncPostReportCount(admin, String(existing.data.post_id));
  return json({ ok: true });
}

async function syncPostReportCount(admin: ReturnType<typeof serviceClient>, postID: string) {
  const pending = await admin.from("post_reports")
    .select("id", { count: "exact", head: true })
    .eq("post_id", postID)
    .eq("status", "pending");
  const reportCount = Number(pending.count ?? 0);
  await admin.from("posts").update({ report_count: reportCount, updated_at: new Date().toISOString() }).eq("id", postID);
}

type MediaProvider = "r2" | "stream";
type MediaFieldKind = "asset" | "cover";

type ResolvedMediaWrite = {
  provider: MediaProvider | null;
  bucket: string | null;
  objectKey: string | null;
};

type ResolveMediaWriteOptions = {
  kind: MediaFieldKind;
  authed: string;
  authorID: string;
  postID: string;
  requireReference: boolean;
  allowStreamProvider: boolean;
};

const STREAM_CUSTOMER_SUBDOMAIN = normalizeBaseURL(Deno.env.get("CLOUDFLARE_STREAM_CUSTOMER_SUBDOMAIN"));

async function resolveMediaWriteFromPayload(
  payload: Record<string, unknown>,
  options: ResolveMediaWriteOptions,
): Promise<{ value: ResolvedMediaWrite } | { error: Response }> {
  const legacyKey = options.kind === "asset" ? "assetRef" : "coverImageRef";
  const providerKey = options.kind === "asset" ? "assetProvider" : "coverProvider";
  const bucketKey = options.kind === "asset" ? "assetBucket" : "coverBucket";
  const objectKeyField = options.kind === "asset" ? "assetObjectKey" : "coverObjectKey";

  const legacyRef = normalizeNullableText(payload[legacyKey]);
  const providerRaw = normalizeNullableText(payload[providerKey]);
  const bucketRaw = normalizeNullableText(payload[bucketKey]);
  const objectKeyRaw = normalizeNullableText(payload[objectKeyField]);

  const hasStructuredField = Boolean(providerRaw || bucketRaw || objectKeyRaw);

  if (legacyRef) {
    return { error: badRequest(`${legacyKey} is no longer accepted. Send ${providerKey}, ${bucketKey}, and ${objectKeyField}.`) };
  }

  let provider: MediaProvider | null = null;
  let bucket: string | null = null;
  let objectKey: string | null = null;

  if (hasStructuredField) {
    // "supabase" is no longer accepted as a write-time provider. All new media
    // must be stored in R2. Legacy supabase rows are read-only (served via
    // MediaURLResolver on the client) but cannot be written back.
    const allowedProviders: MediaProvider[] = options.allowStreamProvider
      ? ["r2", "stream"]
      : ["r2"];
    const parsedProvider = parseProviderValue(providerRaw, allowedProviders);
    if (parsedProvider === "invalid") {
      return { error: badRequest(`${providerKey} is invalid.`) };
    }
    if (!parsedProvider) {
      return { error: badRequest(`${providerKey} is required when using structured media fields.`) };
    }
    if (parsedProvider === "stream" && options.kind === "cover") {
      return { error: badRequest("coverProvider does not support stream.") };
    }

    provider = parsedProvider;
    if (parsedProvider === "stream") {
      if (!objectKeyRaw) return { error: badRequest(`${objectKeyField} is required for stream provider.`) };
      objectKey = objectKeyRaw;
      bucket = null;
    } else {
      if (!bucketRaw || !objectKeyRaw) {
        return { error: badRequest(`${bucketKey} and ${objectKeyField} are required for structured media fields.`) };
      }
      bucket = bucketRaw;
      objectKey = objectKeyRaw;
    }
  }

  if (options.requireReference && (!provider || !objectKey || (provider !== "stream" && !bucket))) {
    return { error: badRequest(`${providerKey}, ${bucketKey}, and ${objectKeyField} are required.`) };
  }

  if (provider && objectKey) {
    const ownershipError = await validatePostObjectOwnership(objectKey, options.authed, options.authorID, options.postID);
    if (ownershipError) return { error: ownershipError };

    if (provider === "r2") {
      if (!R2_BUCKET || !R2_CDN_BASE_URL) {
        return { error: badRequest("R2 media storage is not configured.") };
      }
      if (bucket && bucket !== R2_BUCKET) {
        return { error: badRequest("Unsupported R2 bucket.") };
      }
      bucket = R2_BUCKET;
      const publicURL = buildMediaPublicURL(provider, bucket, objectKey);
      if (!publicURL) {
        return { error: badRequest(`Could not derive ${legacyKey} for R2 media.`) };
      }
      const r2ExistsError = await ensureR2ObjectExists(publicURL);
      if (r2ExistsError) return { error: r2ExistsError };
    }
  }

  return {
    value: {
      provider,
      bucket,
      objectKey,
    },
  };
}


function parseProviderValue(value: string | null, allowed: MediaProvider[]): MediaProvider | null | "invalid" {
  if (!value) return null;
  const normalized = value.trim().toLowerCase();
  if (normalized === "r2" || normalized === "stream") {
    return allowed.includes(normalized) ? normalized : "invalid";
  }
  return "invalid";
}

function buildMediaPublicURL(provider: MediaProvider, bucket: string | null, objectKey: string): string | null {
  const encodedKey = encodeObjectKeyForURL(objectKey);

  if (provider === "r2") {
    if (!R2_CDN_BASE_URL) return null;
    return `${R2_CDN_BASE_URL}/${encodedKey}`;
  }

  if (provider === "stream") {
    if (objectKey.startsWith("http://") || objectKey.startsWith("https://")) {
      return objectKey;
    }
    if (!STREAM_CUSTOMER_SUBDOMAIN) return null;
    if (objectKey.endsWith(".m3u8")) {
      return `${STREAM_CUSTOMER_SUBDOMAIN}/${encodedKey}`;
    }
    return `${STREAM_CUSTOMER_SUBDOMAIN}/${encodedKey}/manifest/video.m3u8`;
  }

  return null;
}

function normalizeNullableText
(value: unknown): string | null {
  if (typeof value !== "string") return null;
  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : null;
}

function normalizeBaseURL(value: string | null | undefined): string | null {
  const normalized = normalizeNullableText(value ?? null);
  if (!normalized) return null;
  return normalized.replace(/\/+$/, "");
}

function encodeObjectKeyForURL(objectKey: string): string {
  return objectKey
    .split("/")
    .filter((segment) => segment.length > 0)
    .map((segment) => encodeURIComponent(segment))
    .join("/");
}

async function validatePostObjectOwnership(
  objectKey: string,
  authed: string,
  authorID: string,
  postID: string,
): Promise<Response | null> {
  const normalizedPath = String(objectKey ?? "").trim().toLowerCase();
  const normalizedPostID = postID.trim().toLowerCase();
  const normalizedAuthed = authed.trim().toLowerCase();
  const normalizedAuthor = authorID.trim().toLowerCase();
  const segments = normalizedPath.split("/").filter(Boolean);

  const ownerID = extractPostOwnerIDFromObjectKey(normalizedPath);
  const legacyMatches = segments.length >= 3 && segments[1] === normalizedPostID;
  const ownerFirstTypedRoot = segments[1] ?? "";
  const ownerFirstTypedMatches = segments.length >= 4 &&
    (ownerFirstTypedRoot === "posts" || ownerFirstTypedRoot === "podcasts" || ownerFirstTypedRoot === "music") &&
    segments[2] === normalizedPostID;
  const typeFirstTypedRoot = segments[0] ?? "";
  const typeFirstTypedMatches = segments.length >= 5 &&
    (typeFirstTypedRoot === "posts" || typeFirstTypedRoot === "podcasts" || typeFirstTypedRoot === "music") &&
    segments[2] === normalizedPostID;
  const typeFirstOwnerOnlyMatches = segments.length >= 3 &&
    (typeFirstTypedRoot === "posts" || typeFirstTypedRoot === "podcasts" || typeFirstTypedRoot === "music") &&
    ownerID === normalizedAuthor;

  if (!ownerID || (!legacyMatches && !ownerFirstTypedMatches && !typeFirstTypedMatches && !typeFirstOwnerOnlyMatches)) {
    return unauthorized();
  }

  if (ownerID === normalizedAuthed || ownerID === normalizedAuthor) {
    return null;
  }
  if (await canActAsAccount(normalizedAuthed, ownerID)) {
    return null;
  }

  return unauthorized();
}

function extractPostOwnerIDFromObjectKey(objectKey: string): string {
  const segments = objectKey.split("/").filter(Boolean);
  if (segments.length < 2) return "";

  const root = segments[0] ?? "";
  if (root === "posts" || root === "podcasts" || root === "music") {
    return segments[1] ?? "";
  }
  return root;
}

async function ensureR2ObjectExists(publicURL: string): Promise<Response | null> {
  try {
    const head = await fetch(publicURL, { method: "HEAD" });
    if (head.ok || head.status === 304) return null;

    // Some CDNs reject HEAD but allow range GET probes.
    const probe = await fetch(publicURL, {
      method: "GET",
      headers: { Range: "bytes=0-0" },
    });
    if (probe.ok || probe.status === 206) return null;

    return badRequest("Referenced R2 object was not found.");
  } catch {
    return badRequest("Could not verify referenced R2 object.");
  }
}

async function updateMedia(req: Request, authed: string) {
  const payload = await req.json();
  const postID = String(payload.postID ?? "").trim();
  const requestedAuthorID = String(payload.authorID ?? "").trim();
  if (!postID) return badRequest("postID required.");

  const authorID = await resolveAuthorIDForWrite(authed, requestedAuthorID);
  if (!authorID) return unauthorized();

  const assetWrite = await resolveMediaWriteFromPayload(payload, {
    kind: "asset",
    authed,
    authorID,
    postID,
    requireReference: true,
    allowStreamProvider: true,
  });
  if ("error" in assetWrite) return assetWrite.error;

  const hasAspectRatio = "aspectRatio" in payload;
  const parsedAspectRatio = Number(payload.aspectRatio);
  if (hasAspectRatio && (!Number.isFinite(parsedAspectRatio) || parsedAspectRatio <= 0)) {
    return badRequest("Invalid aspect ratio.");
  }

  const admin = serviceClient();
  const existing = await admin.from("posts")
    .select("id, author_id, caption, asset_ref, asset_provider, asset_bucket, asset_object_key")
    .eq("id", postID)
    .eq("author_id", authorID)
    .is("deleted_at", null)
    .maybeSingle();
  if (existing.error) return badRequest(existing.error.message);
  if (!existing.data) return unauthorized();

  if (isPodcastCaption(existing.data.caption) && looksLikeVideoObjectKey(assetWrite.value.objectKey)) {
    return badRequest("Podcasts are audio-only on Scrolls.");
  }
  if (isMusicCaption(existing.data.caption)) {
    if (!looksLikeMusicAudioObjectKey(assetWrite.value.objectKey)) {
      return badRequest("Music uploads must be AAC, M4A, or Apollo-bounced WAV audio.");
    }
  }

  const update: Record<string, unknown> = {
    asset_ref: null,
    asset_provider: assetWrite.value.provider,
    asset_bucket: assetWrite.value.bucket,
    asset_object_key: assetWrite.value.objectKey,
    updated_at: new Date().toISOString(),
  };
  if (hasAspectRatio) {
    update.aspect_ratio = parsedAspectRatio;
  }

  const write = await admin.from("posts")
    .update(update)
    .eq("id", postID)
    .eq("author_id", authorID);
  if (write.error) return badRequest(write.error.message);

  await removeReplacedStorageRefsIfNeeded(
    admin,
    collectLegacyRefs(existing.data.asset_ref),
    collectStructuredRefs(existing.data.asset_provider, existing.data.asset_bucket, existing.data.asset_object_key),
    [],
    collectStructuredRefs(assetWrite.value.provider, assetWrite.value.bucket, assetWrite.value.objectKey),
  );

  return json({ ok: true });
}

async function updateCoverImage(req: Request, authed: string) {
  const payload = await req.json();
  const postID = String(payload.postID ?? "").trim();
  const requestedAuthorID = String(payload.authorID ?? "").trim();

  if (!postID) {
    return badRequest("postID required.");
  }

  const authorID = await resolveAuthorIDForWrite(authed, requestedAuthorID);
  if (!authorID) return unauthorized();

  const coverWrite = await resolveMediaWriteFromPayload(payload, {
    kind: "cover",
    authed,
    authorID,
    postID,
    requireReference: true,
    allowStreamProvider: false,
  });
  if ("error" in coverWrite) return coverWrite.error;

  const admin = serviceClient();
  const existing = await admin.from("posts")
    .select("id, author_id, cover_image_ref, cover_provider, cover_bucket, cover_object_key")
    .eq("id", postID)
    .eq("author_id", authorID)
    .is("deleted_at", null)
    .maybeSingle();
  if (existing.error) return badRequest(existing.error.message);
  if (!existing.data) return unauthorized();

  const write = await admin.from("posts")
    .update({
      cover_image_ref: null,
      cover_provider: coverWrite.value.provider,
      cover_bucket: coverWrite.value.bucket,
      cover_object_key: coverWrite.value.objectKey,
      updated_at: new Date().toISOString(),
    })
    .eq("id", postID)
    .eq("author_id", authorID);
  if (write.error) return badRequest(write.error.message);

  await removeReplacedStorageRefsIfNeeded(
    admin,
    collectLegacyRefs(existing.data.cover_image_ref),
    collectStructuredRefs(existing.data.cover_provider, existing.data.cover_bucket, existing.data.cover_object_key),
    [],
    collectStructuredRefs(coverWrite.value.provider, coverWrite.value.bucket, coverWrite.value.objectKey),
  );

  return json({ ok: true });
}
async function updateCaption(req: Request, authed: string) {
  const payload = await req.json();
  const postID = String(payload.postID ?? "").trim();
  const requestedAuthorID = String(payload.authorID ?? "").trim();
  if (!postID) return badRequest("postID required.");

  const authorID = await resolveAuthorIDForWrite(authed, requestedAuthorID);
  if (!authorID) return unauthorized();

  // Apply the same content-moderation rules as post creation.
  const newCaption = "caption" in payload
    ? (typeof payload.caption === "string" ? payload.caption.trim() : null)
    : undefined;
  if (typeof newCaption === "string" && newCaption.length > 0) {
    const visibleCaption = visibleCaptionForValidation(newCaption);
    if (containsBlockedAIText(newCaption)) return badRequest("AI-generated content is not allowed.");
    if (containsBlockedNudityText(newCaption)) return badRequest("Explicit nudity content is not allowed.");
    if (visibleCaption.length > 220) return badRequest("Caption too long.");
  }

  const admin = serviceClient();
  const existing = await admin.from("posts")
    .select("id, author_id, caption, asset_object_key, subscription_unlocked_at")
    .eq("id", postID)
    .eq("author_id", authorID)
    .is("deleted_at", null)
    .maybeSingle();
  if (existing.error) return badRequest(existing.error.message);
  if (!existing.data) return unauthorized();

  if (typeof newCaption === "string" && isPodcastCaption(newCaption) && looksLikeVideoObjectKey(existing.data.asset_object_key)) {
    return badRequest("Podcasts are audio-only on Scrolls.");
  }
  if (typeof newCaption === "string" && isMusicCaption(newCaption)) {
    if (!looksLikeMusicAudioObjectKey(existing.data.asset_object_key)) {
      return badRequest("Music uploads must be AAC, M4A, or Apollo-bounced WAV audio.");
    }
    const allowanceError = await validateMusicUploadAllowance(admin, authorID, newCaption, postID);
    if (allowanceError) return allowanceError;
  }

  const update: Record<string, unknown> = { updated_at: new Date().toISOString() };
  if (typeof newCaption !== "undefined") {
    update.caption = (typeof newCaption === "string" && newCaption.length > 0) ? newCaption : null;
    update.subscription_unlocked_at = isSubscriptionUnlockedCaption(newCaption)
      ? (existing.data.subscription_unlocked_at ?? await subscriptionUnlockedTimestampForAuthor(admin, authorID, newCaption))
      : null;
  }
  if ("locationCity" in payload) {
    const city = typeof payload.locationCity === "string" ? payload.locationCity.trim() : null;
    update.location_city = city && city.length > 0 ? city : null;
  }

  const write = await admin.from("posts").update(update).eq("id", postID).eq("author_id", authorID);
  if (write.error) return badRequest(write.error.message);

  if (typeof newCaption === "string" && isMusicCaption(newCaption)) {
    const oldMusicTracks = parseMusicTrackMetadata(existing.data.caption);
    const newMusicTracks = parseMusicTrackMetadata(newCaption);
    await removeReplacedStorageRefsIfNeeded(
      admin,
      oldMusicTracks.map((t) => t.audioURL).filter((u): u is string => u !== null),
      [],
      newMusicTracks.map((t) => t.audioURL).filter((u): u is string => u !== null),
      [],
    );
  }

  // Notify any collaborators added by this edit (diff against the old
  // caption so re-saves don't re-spam users who were tagged earlier).
  if (typeof newCaption === "string") {
    try {
      const previous = new Set(collaboratorIDsFromCaption(existing.data.caption));
      const updated = collaboratorIDsFromCaption(newCaption);
      const added = updated.filter((id) => !previous.has(id));
      if (added.length > 0) {
        // Re-encode just the additions into a stripped marker string so
        // notifyCollaborators can reuse its existing decoder path.
        const markerPayload = btoa(JSON.stringify(added));
        await notifyCollaborators(
          admin,
          postID,
          authorID,
          `[SCROLL_COLLABORATORS_BASE64] ${markerPayload}`,
        );
      }
    } catch (collabError) {
      console.error(JSON.stringify({
        event:   "collaborator_notification_edit_error",
        post_id: postID,
        error:   String(collabError),
      }));
    }
  }

  return json({ ok: true });
}

type StructuredStorageRef = {
  provider: "supabase" | "r2";
  bucket: string;
  objectKey: string;
};

type MusicTrackCaptionMetadata = {
  title: string;
  audioURL: string | null;
};

function parseMusicTrackMetadata(caption: string | null): MusicTrackCaptionMetadata[] {
  const raw = typeof caption === "string" ? caption.trim() : "";
  if (!raw) return [];
  const upper = raw.toUpperCase();
  if (!upper.startsWith("[MUSIC]")) return [];
  const lines = raw
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line.length > 0);
  const prefix = "[MUSIC_TRACKS_BASE64]";
  for (const line of lines) {
    if (!line.toUpperCase().startsWith(prefix)) continue;
    const encoded = line.slice(prefix.length).trim();
    if (!encoded) return [];
    try {
      const decoded = JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(encoded), (char) => char.charCodeAt(0)))) as Array<Record<string, unknown>>;
      return decoded.map((item) => ({
        title: typeof item.title === "string" ? item.title : "",
        audioURL: typeof item.audioURL === "string" && item.audioURL.trim().length > 0 ? item.audioURL.trim() : null,
      }));
    } catch {
      return [];
    }
  }
  return [];
}

function collectLegacyRefs(...refs: Array<string | null | undefined>): string[] {
  return refs
    .map((ref) => typeof ref === "string" ? ref.trim() : "")
    .filter((ref) => ref.length > 0);
}

function collectStructuredRefs(
  provider: string | null | undefined,
  bucket: string | null | undefined,
  objectKey: string | null | undefined,
): StructuredStorageRef[] {
  const normalizedProvider = provider?.trim().toLowerCase();
  const normalizedBucket = bucket?.trim() ?? "";
  const normalizedObjectKey = objectKey?.trim() ?? "";
  if (!normalizedProvider || !normalizedBucket || !normalizedObjectKey) return [];
  if (normalizedProvider !== "supabase" && normalizedProvider !== "r2") return [];
  return [{
    provider: normalizedProvider,
    bucket: normalizedBucket,
    objectKey: normalizedObjectKey,
  }];
}

async function removeReplacedStorageRefsIfNeeded(
  admin: ReturnType<typeof serviceClient>,
  previousLegacyRefs: string[],
  previousStructuredRefs: StructuredStorageRef[],
  nextLegacyRefs: string[],
  nextStructuredRefs: StructuredStorageRef[],
) {
  const nextKeys = new Set<string>();
  for (const ref of nextLegacyRefs) {
    const parsedSupabase = parseStoragePublicURL(ref);
    if (parsedSupabase) {
      nextKeys.add(`supabase:${parsedSupabase.bucket}:${parsedSupabase.path}`);
      continue;
    }
    const parsedR2 = parseR2ObjectKeyFromPublicURL(ref);
    if (parsedR2 && R2_BUCKET) {
      nextKeys.add(`r2:${R2_BUCKET}:${parsedR2}`);
    }
  }
  for (const structured of nextStructuredRefs) {
    nextKeys.add(`${structured.provider}:${structured.bucket}:${structured.objectKey}`);
  }

  const refsToDeleteLegacy: string[] = [];
  const refsToDeleteStructured: StructuredStorageRef[] = [];

  for (const ref of previousLegacyRefs) {
    const parsedSupabase = parseStoragePublicURL(ref);
    if (parsedSupabase) {
      const key = `supabase:${parsedSupabase.bucket}:${parsedSupabase.path}`;
      if (!nextKeys.has(key)) refsToDeleteLegacy.push(ref);
      continue;
    }
    const parsedR2 = parseR2ObjectKeyFromPublicURL(ref);
    if (parsedR2 && R2_BUCKET) {
      const key = `r2:${R2_BUCKET}:${parsedR2}`;
      if (!nextKeys.has(key)) refsToDeleteLegacy.push(ref);
    }
  }

  for (const structured of previousStructuredRefs) {
    const key = `${structured.provider}:${structured.bucket}:${structured.objectKey}`;
    if (!nextKeys.has(key)) refsToDeleteStructured.push(structured);
  }

  if (refsToDeleteLegacy.length === 0 && refsToDeleteStructured.length === 0) return;
  await purgeStorageRefs(admin, refsToDeleteLegacy, refsToDeleteStructured);
}

async function purgeStorageRefs(
  admin: ReturnType<typeof serviceClient>,
  legacyRefs: Array<string | null>,
  structuredRefs: StructuredStorageRef[],
) {
  const targets = collectStorageTargets(legacyRefs, structuredRefs);
  await removeSupabaseStorageTargets(admin, targets.supabaseByBucket);
  await deleteR2Objects(Array.from(targets.r2ObjectKeys));
}

async function quarantineDeletedPostStorageRefs(
  admin: ReturnType<typeof serviceClient>,
  legacyRefs: Array<string | null>,
  structuredRefs: StructuredStorageRef[],
  context: { postID: string; authorID: string },
) {
  const targets = collectStorageTargets(legacyRefs, structuredRefs);
  await removeSupabaseStorageTargets(admin, targets.supabaseByBucket);
  await quarantineR2ObjectsForDeletedPost(Array.from(targets.r2ObjectKeys), context);
}

function collectStorageTargets(
  legacyRefs: Array<string | null>,
  structuredRefs: StructuredStorageRef[],
): { supabaseByBucket: Map<string, Set<string>>; r2ObjectKeys: Set<string> } {
  const supabaseByBucket = new Map<string, Set<string>>();
  const r2ObjectKeys = new Set<string>();

  const ingestTarget = (target: StructuredStorageRef | null) => {
    if (!target) return;
    const bucket = target.bucket.trim();
    const objectKey = target.objectKey.trim();
    if (!bucket || !objectKey) return;
    if (target.provider === "supabase") {
      const set = supabaseByBucket.get(bucket) ?? new Set<string>();
      set.add(objectKey);
      supabaseByBucket.set(bucket, set);
      return;
    }
    if (target.provider === "r2") {
      r2ObjectKeys.add(objectKey);
    }
  };

  for (const ref of legacyRefs) {
    if (!ref) continue;
    const supabaseParsed = parseStoragePublicURL(ref);
    if (supabaseParsed) {
      ingestTarget({ provider: "supabase", bucket: supabaseParsed.bucket, objectKey: supabaseParsed.path });
      continue;
    }
    const r2ObjectKey = parseR2ObjectKeyFromPublicURL(ref);
    if (r2ObjectKey && R2_BUCKET) {
      ingestTarget({ provider: "r2", bucket: R2_BUCKET, objectKey: r2ObjectKey });
    }
  }

  for (const structured of structuredRefs) {
    ingestTarget(structured);
  }

  return { supabaseByBucket, r2ObjectKeys };
}

async function removeSupabaseStorageTargets(
  admin: ReturnType<typeof serviceClient>,
  supabaseByBucket: Map<string, Set<string>>,
) {
  for (const [bucket, keys] of supabaseByBucket.entries()) {
    const objects = Array.from(keys);
    for (let i = 0; i < objects.length; i += 50) {
      await admin.storage.from(bucket).remove(objects.slice(i, i + 50));
    }
  }
}

function parseR2ObjectKeyFromPublicURL(assetRef: string): string | null {
  if (!R2_CDN_BASE_URL) return null;
  try {
    const parsed = new URL(assetRef);
    const base = new URL(R2_CDN_BASE_URL);
    if (parsed.origin !== base.origin) return null;
    const objectKey = decodeURIComponent(parsed.pathname.replace(/^\/+/, "")).trim();
    return objectKey.length > 0 ? objectKey : null;
  } catch {
    return null;
  }
}

function createR2Client(): S3Client | null {
  if (!R2_ACCOUNT_ID || !R2_ACCESS_KEY_ID || !R2_SECRET_ACCESS_KEY) {
    return null;
  }
  return new S3Client({
    region: "auto",
    endpoint: `https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com`,
    credentials: {
      accessKeyId: R2_ACCESS_KEY_ID,
      secretAccessKey: R2_SECRET_ACCESS_KEY,
    },
    forcePathStyle: true,
  });
}

async function deleteR2Objects(objectKeys: string[]): Promise<void> {
  const keys = Array.from(new Set(
    objectKeys.map((value) => value.trim()).filter((value) => value.length > 0),
  ));
  if (keys.length === 0) return;
  const client = createR2Client();
  if (!client || !R2_BUCKET) {
    console.warn("posts: r2 delete skipped because R2 credentials or bucket are missing", {
      hasClient: client !== null,
      hasBucket: Boolean(R2_BUCKET),
      attemptedKeys: keys.length,
    });
    return;
  }

  for (let i = 0; i < keys.length; i += 1000) {
    const chunk = keys.slice(i, i + 1000).map((key) => ({ Key: key }));
    try {
      await client.send(new DeleteObjectsCommand({
        Bucket: R2_BUCKET,
        Delete: {
          Objects: chunk,
          Quiet: true,
        },
      }));
    } catch (error) {
      console.warn("posts: r2 delete failed", error);
    }
  }
}

async function quarantineR2ObjectsForDeletedPost(
  objectKeys: string[],
  context: { postID: string; authorID: string },
): Promise<void> {
  const keys = Array.from(new Set(
    objectKeys
      .map((value) => normalizeR2ObjectKey(value))
      .filter((value): value is string => value !== null && !value.startsWith("deleted-posts/")),
  ));
  const client = createR2Client();
  if (!client || !R2_BUCKET) {
    console.warn("posts: r2 deleted-post quarantine skipped because R2 credentials or bucket are missing", {
      hasClient: client !== null,
      hasBucket: Boolean(R2_BUCKET),
      attemptedKeys: keys.length,
      postID: context.postID,
    });
    return;
  }

  const copiedKeys: string[] = [];
  for (const sourceKey of keys) {
    const destinationKey = deletedPostR2ObjectKey(context, sourceKey);
    try {
      await client.send(new CopyObjectCommand({
        Bucket: R2_BUCKET,
        CopySource: `${R2_BUCKET}/${encodeR2CopySourceKey(sourceKey)}`,
        Key: destinationKey,
        MetadataDirective: "COPY",
      }));
      copiedKeys.push(sourceKey);
    } catch (error) {
      console.warn("posts: r2 deleted-post quarantine copy failed", {
        postID: context.postID,
        authorID: context.authorID,
        sourceKey,
        destinationKey,
        error: error instanceof Error ? error.message : String(error),
      });
    }
  }

  if (copiedKeys.length > 0) {
    await deleteR2Objects(copiedKeys);
  }

  const manifestKey = await writeDeletedPostR2Manifest(client, context, keys, copiedKeys);

  console.log(JSON.stringify({
    event: "delete_post_r2_quarantine_complete",
    post_id: context.postID,
    author_id: context.authorID,
    attempted: keys.length,
    copied: copiedKeys.length,
    skipped_or_failed: keys.length - copiedKeys.length,
    manifest_key: manifestKey,
    prefix: `deleted-posts/${deletedPostR2PathSegment(context.authorID)}/${deletedPostR2PathSegment(context.postID)}/`,
  }));
}

async function writeDeletedPostR2Manifest(
  client: S3Client,
  context: { postID: string; authorID: string },
  attemptedKeys: string[],
  copiedKeys: string[],
): Promise<string | null> {
  const manifestKey = [
    "deleted-posts",
    deletedPostR2PathSegment(context.authorID),
    deletedPostR2PathSegment(context.postID),
    "manifest.json",
  ].join("/");
  try {
    await client.send(new PutObjectCommand({
      Bucket: R2_BUCKET,
      Key: manifestKey,
      Body: new TextEncoder().encode(JSON.stringify({
        postID: context.postID,
        authorID: context.authorID,
        deletedAt: new Date().toISOString(),
        sourceObjectKeys: attemptedKeys,
        copiedObjectKeys: copiedKeys.map((sourceKey) => deletedPostR2ObjectKey(context, sourceKey)),
        skippedOrFailedSourceObjectKeys: attemptedKeys.filter((sourceKey) => !copiedKeys.includes(sourceKey)),
      }, null, 2)),
      ContentType: "application/json",
      CacheControl: "no-store",
    }));
    return manifestKey;
  } catch (error) {
    console.warn("posts: r2 deleted-post manifest write failed", {
      postID: context.postID,
      authorID: context.authorID,
      manifestKey,
      error: error instanceof Error ? error.message : String(error),
    });
    return null;
  }
}

function deletedPostR2ObjectKey(context: { postID: string; authorID: string }, sourceKey: string): string {
  return [
    "deleted-posts",
    deletedPostR2PathSegment(context.authorID),
    deletedPostR2PathSegment(context.postID),
    sourceKey,
  ].join("/");
}

function deletedPostR2PathSegment(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, "-")
    .replace(/^-+|-+$/g, "") || "unknown";
}

function normalizeR2ObjectKey(value: string): string | null {
  const normalized = value.trim().replace(/^\/+/, "");
  return normalized.length > 0 ? normalized : null;
}

function encodeR2CopySourceKey(objectKey: string): string {
  return objectKey.split("/").map((part) => encodeURIComponent(part)).join("/");
}

function parseStoragePublicURL(assetRef: string): { bucket: string; path: string } | null {
  try {
    const parsed = new URL(assetRef);
    const marker = "/storage/v1/object/public/";
    const index = parsed.pathname.indexOf(marker);
    if (index == -1) return null;
    const tail = parsed.pathname.slice(index + marker.length);
    const slash = tail.indexOf("/");
    if (slash <= 0) return null;
    const bucket = tail.slice(0, slash);
    const path = tail.slice(slash + 1);
    if (!bucket || !path) return null;
    return { bucket, path };
  } catch {
    return null;
  }
}

async function postsByAuthor(url: URL, viewerIDRaw: string | null = null) {
  const authorID = String(url.searchParams.get("author_id") ?? "").trim().toLowerCase();
  if (!authorID) return badRequest("author_id required.");
  const cursor = String(url.searchParams.get("cursor") ?? "").trim() || null;
  const viewerID = String(viewerIDRaw ?? "").trim().toLowerCase();
  const isPublicRequest = !viewerID;
  const requestedLimit = Number(url.searchParams.get("limit") ?? (isPublicRequest ? "20" : "50"));
  const limit = Math.max(
    1,
    Math.min(Number.isFinite(requestedLimit) ? requestedLimit : (isPublicRequest ? 20 : 50), isPublicRequest ? 24 : 100),
  );

  const admin = serviceClient();
  const userMap = await fetchUsersByIds([authorID]);
  const author = userMap[authorID];
  if (!author) return json({ posts: [], nextCursor: null });

  if (author.isPrivate && !await canViewPrivateAuthorPosts(admin, viewerID, authorID)) {
    return json({ posts: [], nextCursor: null });
  }

  let query = admin.from("posts")
    .select(POST_LIST_COLUMNS)
    .eq("author_id", authorID)
    .is("deleted_at", null)
    .order("created_at", { ascending: false })
    .limit(limit + 1);
  if (cursor) {
    query = query.lt("created_at", cursor);
  }

  const result = await query;
  if (result.error) return badRequest(result.error.message);

  const rows = (result.data ?? []) as Record<string, unknown>[];
  const tombstonedPostIDs = await fetchDeletedPostIDSet(
    admin,
    rows.map((row) => String(row.id ?? "")),
  );
  const visibleRows = rows.filter((row) => !tombstonedPostIDs.has(String(row.id ?? "").trim().toLowerCase()));
  const pageRows = visibleRows.slice(0, limit);
  const hasMore = visibleRows.length > limit;

  let effectivePageRows = pageRows;
  const pinnedPostID = String(author.pinnedPostID ?? "").trim().toLowerCase();
  if (!cursor && pinnedPostID && !effectivePageRows.some((row) => String(row.id ?? "").trim().toLowerCase() === pinnedPostID)) {
    const pinned = await admin.from("posts")
      .select(POST_LIST_COLUMNS)
      .eq("id", pinnedPostID)
      .eq("author_id", authorID)
      .is("deleted_at", null)
      .maybeSingle();
    if (!pinned.error && pinned.data && !tombstonedPostIDs.has(pinnedPostID)) {
      effectivePageRows = [pinned.data as Record<string, unknown>, ...effectivePageRows];
    }
  }

  const mapped = effectivePageRows.map((row) => mapPost(row, author));
  const responsePosts = isPublicRequest ? mapped.map(compactPostForPublicList) : mapped;
  const nextCursor = hasMore && mapped.length > 0
    ? new Date(String(pageRows[Math.max(0, pageRows.length - 1)]?.created_at ?? mapped[mapped.length - 1].createdAt)).toISOString()
    : null;
  const deletedPostIDs = await fetchDeletedPostIDsForAuthorIDs(admin, [authorID]);

  return json({ posts: responsePosts, nextCursor, deletedPostIDs });
}

/**
 * Lists a user's rescrolls as feed-shaped posts (id = rescroll id, author =
 * the rescroller, rescrollOrigin = the original post's author/caption, with the
 * optional quote text). Mirrors the rescroll assembly in the feed function so
 * the profile Rescrolls tab matches the home feed. Public, like by-author.
 */
async function rescrollsByAuthor(url: URL) {
  const authorID = String(url.searchParams.get("author_id") ?? "").trim().toLowerCase();
  if (!authorID) return badRequest("author_id required.");
  const requestedLimit = Number(url.searchParams.get("limit") ?? "20");
  const limit = Math.max(1, Math.min(Number.isFinite(requestedLimit) ? requestedLimit : 20, 24));

  const admin = serviceClient();
  const rescrollResult = await admin.from("rescrolls")
    .select("id, original_post_id, quote_text, created_at")
    .eq("user_id", authorID)
    .order("created_at", { ascending: false })
    .limit(limit);
  if (rescrollResult.error) return badRequest(rescrollResult.error.message);
  const rescrollRows = (rescrollResult.data ?? []) as Record<string, unknown>[];
  if (rescrollRows.length === 0) return json({ posts: [], nextCursor: null });

  const postIDs = Array.from(
    new Set(rescrollRows.map((row) => String(row.original_post_id ?? "").trim().toLowerCase()).filter(Boolean)),
  );
  const postsResult = await admin.from("posts").select(POST_LIST_COLUMNS).in("id", postIDs).is("deleted_at", null);
  if (postsResult.error) return badRequest(postsResult.error.message);
  const postRows = (postsResult.data ?? []) as Record<string, unknown>[];
  const tombstoned = await fetchDeletedPostIDSet(admin, postRows.map((row) => String(row.id ?? "")));
  const postsByID = new Map(
    postRows
      .filter((row) => !tombstoned.has(String(row.id ?? "").trim().toLowerCase()))
      .map((row) => [String(row.id ?? "").trim().toLowerCase(), row]),
  );

  const authorIDs = new Set<string>([authorID]);
  for (const row of postsByID.values()) authorIDs.add(String(row.author_id ?? "").trim().toLowerCase());
  const userMap = await fetchUsersByIds(Array.from(authorIDs).filter(Boolean));
  const rescroller = userMap[authorID];
  if (!rescroller) return json({ posts: [], nextCursor: null });

  const mapped = rescrollRows
    .map((row) => {
      const post = postsByID.get(String(row.original_post_id ?? "").trim().toLowerCase());
      if (!post) return null;
      const originalAuthor = userMap[String(post.author_id ?? "").trim().toLowerCase()];
      if (!originalAuthor) return null;
      const originalPostID = String(row.original_post_id ?? "");
      return mapPost(
        {
          ...post,
          id: String(row.id ?? ""),
          quote_text: String(row.quote_text ?? "").trim() || null,
          created_at: new Date(String(row.created_at ?? "")).toISOString(),
        },
        rescroller,
        {
          postID: originalPostID,
          user: originalAuthor,
          caption: (post.caption as string | null) ?? null,
          websiteURL: (post.website_url as string | null) ?? null,
          timestamp: new Date(String(post.created_at)).toISOString(),
        },
      );
    })
    .filter(Boolean) as ReturnType<typeof mapPost>[];

  return json({ posts: mapped.map(compactPostForPublicList), nextCursor: null });
}

async function canViewPrivateAuthorPosts(
  admin: ReturnType<typeof serviceClient>,
  viewerID: string,
  authorID: string,
): Promise<boolean> {
  if (!viewerID) return false;
  if (viewerID === authorID) return true;
  const follow = await admin.from("follows")
    .select("id")
    .eq("follower_id", viewerID)
    .eq("followee_id", authorID)
    .eq("status", "accepted")
    .limit(1)
    .maybeSingle();
  return !follow.error && Boolean(follow.data);
}

async function postByID(url: URL) {
  const postID = String(
    url.searchParams.get("id") ??
      url.searchParams.get("post_id") ??
      url.searchParams.get("postID") ??
      "",
  ).trim().toLowerCase();
  if (!postID) return badRequest("post id is required.");

  const admin = serviceClient();
  const tombstoned = await fetchDeletedPostIDSet(admin, [postID]);
  if (tombstoned.has(postID)) return notFound();

  const post = await admin.from("posts")
    .select("*")
    .eq("id", postID)
    .is("deleted_at", null)
    .maybeSingle();
  if (post.error) return badRequest(post.error.message);
  if (!post.data) return notFound();

  const authorID = String(post.data.author_id ?? "").trim().toLowerCase();
  if (!authorID) return notFound();

  const users = await fetchUsersByIds([authorID]);
  const author = users[authorID];
  if (!author || author.isPrivate) return notFound();

  return json({ post: mapPost(post.data as Record<string, unknown>, author) });
}

async function fetchDeletedPostIDsForAuthorIDs(
  admin: ReturnType<typeof serviceClient>,
  authorIDs: string[],
): Promise<string[]> {
  const normalizedAuthorIDs = Array.from(new Set(
    authorIDs.map((value) => String(value).trim().toLowerCase()).filter(Boolean),
  ));
  if (normalizedAuthorIDs.length === 0) return [];

  const cutoff = new Date(Date.now() - POST_TOMBSTONE_LOOKBACK_DAYS * 24 * 60 * 60 * 1000).toISOString();
  const tombstones = await admin.from("deleted_post_tombstones")
    .select("post_id")
    .in("author_id", normalizedAuthorIDs)
    .gte("deleted_at", cutoff)
    .order("deleted_at", { ascending: false })
    .limit(POST_TOMBSTONE_LIMIT);
  if (tombstones.error || !tombstones.data) return [];
  return Array.from(new Set(
    tombstones.data
      .map((row) => String(row.post_id ?? "").trim().toLowerCase())
      .filter((value) => value.length > 0),
  ));
}

async function fetchDeletedPostIDSet(
  admin: ReturnType<typeof serviceClient>,
  postIDs: string[],
): Promise<Set<string>> {
  const ids = Array.from(new Set(
    postIDs.map((value) => String(value).trim().toLowerCase()).filter(Boolean),
  ));
  if (ids.length === 0) return new Set();

  const tombstones = await admin.from("deleted_post_tombstones")
    .select("post_id")
    .in("post_id", ids);
  if (tombstones.error || !tombstones.data) return new Set();
  return new Set(
    tombstones.data
      .map((row) => String(row.post_id ?? "").trim().toLowerCase())
      .filter((value) => value.length > 0),
  );
}

async function commentsForPost(postID: string) {
  const admin = serviceClient();
  const rows = await admin.from("comments")
    .select("*")
    .eq("post_id", postID)
    .is("deleted_at", null)
    .order("created_at", { ascending: true });
  if (rows.error) return badRequest(rows.error.message);
  const comments = rows.data ?? [];
  const userIDs = Array.from(new Set(comments.map((row) => String(row.author_id))));
  const users = await fetchUsersByIds(userIDs);

  const commentIDs = comments.map((c) => c.id);
  const likesRows = commentIDs.length > 0
    ? await admin.from("comment_likes")
      .select("*")
      .in("comment_id", commentIDs)
    : { data: [], error: null };

  const likesByComment: Record<string, string[]> = {};
  for (const row of likesRows.data ?? []) {
    const commentID = String(row.comment_id);
    likesByComment[commentID] = likesByComment[commentID] ?? [];
    likesByComment[commentID].push(String(row.user_id));
  }

  const normalizedLikedBy = (value: unknown): string[] => {
    if (!Array.isArray(value)) return [];
    return value
      .map((entry) => String(entry ?? "").trim())
      .filter((entry) => entry.length > 0);
  };

  const mapByID: Record<string, Record<string, unknown>> = {};
  const roots: Record<string, unknown>[] = [];
  for (const row of comments) {
    const author = users[String(row.author_id)];
    if (!author) {
      // Legacy safety: skip orphaned comments instead of returning invalid payloads.
      continue;
    }
    mapByID[String(row.id)] = {
      id: String(row.id),
      author,
      body: String(row.body ?? ""),
      createdAt: new Date(String(row.created_at)).toISOString(),
      likedBy: normalizedLikedBy(likesByComment[String(row.id)] ?? []),
      replies: [],
      parentCommentID: row.parent_comment_id ? String(row.parent_comment_id) : null,
    };
  }
  for (const row of Object.values(mapByID)) {
    const parentID = row.parentCommentID as string | null;
    if (parentID && mapByID[parentID]) {
      const replies = mapByID[parentID].replies as Record<string, unknown>[];
      replies.push(row);
    } else {
      roots.push(row);
    }
  }
  const prune = (node: Record<string, unknown>): Record<string, unknown> => ({
    id: node.id,
    author: node.author,
    body: node.body,
    createdAt: node.createdAt,
    likedBy: normalizedLikedBy(node.likedBy),
    replies: (node.replies as Record<string, unknown>[]).map(prune),
  });
  return json(roots.map(prune));
}
